# Dockerfile for building image that contains software stack provisioned by Ansible.
#
# USAGE:
#   $ docker build -t fluentd .
#   $ docker run -p 24220:24220 fluentd
#
# Version  1.0
#


# pull base image
FROM williamyeh/ansible:ubuntu14.04-onbuild

MAINTAINER William Yeh <william.pjyeh@gmail.com>


#
# build phase
#

ENV PLAYBOOK test.yml
RUN ansible-playbook-wrapper

# port for monitoring agent
EXPOSE 24220


#
# test phase
#

RUN echo "===> Installing curl for testing purpose..."  && \
    DEBIAN_FRONTEND=noninteractive  \
    apt-get install -y -f curl


CMD [ "/opt/td-agent/embedded/bin/ruby", "/usr/sbin/td-agent", "--use-v1-config" ]
