---
# file: tasks/main.yml
# Top-level installer for Fluentd.
#
# @see http://docs.treasuredata.com/articles/td-agent
#

- name: set role variables, if necessary
  include: set-role-variables.yml


- name: delegate to APT system for installation
  include: use-apt.yml
  when: ansible_pkg_mgr == "apt"

- name: delegate to YUM system for installation
  include: use-yum.yml
  when: ansible_pkg_mgr == "yum"




- name: mkdir for conf.d
  file:
    path: /etc/td-agent/conf.d
    state: directory
    owner: td-agent
    group: td-agent
    mode: "0700"

- name: rename default td-agent.conf
  command: creates="/etc/td-agent/td-agent.conf.bak" mv /etc/td-agent/td-agent.conf /etc/td-agent/td-agent.conf.bak



- name: copy new td-agent.conf from role's default
  copy:
    src: ../files/td-agent.conf
    dest: /etc/td-agent/td-agent.conf
    owner: td-agent
    group: td-agent
    mode: "0600"
  when: tdagent_conf_copy is not defined and tdagent_conf_template is not defined
  notify:
    - reload td-agent

- name: copy new "td-agent.conf" verbatim from main playbook's
  copy:
    src:  "{{ playbook_dir }}/{{ tdagent_conf_copy }}"
    dest: /etc/td-agent/td-agent.conf
    owner: td-agent
    group: td-agent
    mode: "0600"
  when: tdagent_conf_copy is defined
  notify:
    - reload td-agent

- name: copy (from template) new "td-agent.conf" from main playbook's
  template:
    src:  "{{ playbook_dir }}/{{ tdagent_conf_template }}"
    dest: /etc/td-agent/td-agent.conf
    owner: td-agent
    group: td-agent
    mode: "0600"
  when: tdagent_conf_template is defined
  notify:
    - reload td-agent

- name: copy other config files from playbook's, if any
  template:
    src:  "{{ playbook_dir }}/{{ item.value.src }}"
    dest: "/etc/td-agent/conf.d/{{ item.value.dest }}"
    owner: td-agent
    group: td-agent
    mode: "0600"
  with_dict: '{{ tdagent_conf_others | default({}) }}'
  notify:
    - reload td-agent




# GEM installed on:
#   /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/
- name: install plugins, if any
  gem:
      name: "{{ item }}"
      executable: /opt/td-agent/embedded/bin/fluent-gem
      state: latest
      user_install: no
  with_items: "{{ tdagent_plugins | default([]) }}"
  notify:
    - restart td-agent


- name: install plugins with specified versions, if any
  gem:
      name: "{{ item.value.name }}"
      executable: /opt/td-agent/embedded/bin/fluent-gem
      state: present
      version: "{{ item.value.version }}"
      user_install: no
  with_dict: "{{ tdagent_plugins_versions | default({}) }}"
  notify:
    - restart td-agent

